#include <cstdlib>
#include <string>
#include <time.h>

//200 most popular boy's and girl's names for 2016.
//Source: Babycenter.

const int FNAME_NUM = 200;
const int LNAME_NUM = 400; //Make it possible for each person to have a different last name.

string boyFirstNames[FNAME_NUM] = {"Liam", "Noah", "Ethan", "Mason", "Lucas", "Logan", "Oliver", "Jackson", "Aiden", "Jacob", "Elijah", "James", "Benjamin", "Alexander", "Jack", "Luke", "William", "Carter", "Michael", "Daniel", "Owen", "Gabriel", "Henry", "Matthew", "Wyatt", "Jayden", "Nathan", "Isaac", "Ryan", "Caleb", "Sebastian", "David", "Andrew", "Dylan", "Samuel", "Connor", "Joshua", "Eli", "Hunter", "Jaxon", "Nicolas", "Angel", "Avery", "Bradley", "Miguel", "Giovanni", "Dean", "Kevin", "Eric", "Omar", "Preston", "A.J.", "Antonio", "Ali", "Elliott", "Diego", "Sean", "Ezekiel", "Justin", "Grant", "Ivan", "Matteo", "Brady", "Lorenzo", "Axel", "Joel", "Elliot", "Maverick", "Arthur", "Juan", "Jose", "Enzo", "Rowan", "Beau", "Cayden", "Luis", "Zane", "Tucker", "Jaden", "Jasper", "Grayson", "Levi", "Landon", "Anthony", "Joseph", "Julian", "Max", "John", "Adam", "Christian", "Cameron", "Gavin", "Leo", "Lincoln", "Isaiah", "Evan", "Nolan", "Muhammad", "Hudson", "Dominic", "Thomas", "Brayden", "Christopher", "Colton", "Aaron", "Parker", "Austin", "Nicholas", "Adrian", "Charlie", "Josiah", "Tyler", "Cooper", "Jonathan", "Asher", "Jordan", "Chase", "Jace", "Jeremiah", "Jaxson", "Alex", "Ian", "Easton", "Zachary", "Ezra", "Carson", "Xavier", "Miles", "Blake", "Declan", "Ayden", "Tristan", "Cole", "Nathaniel", "Micah", "Ryder", "Jason", "Harrison", "Sawyer", "Mateo", "Brody", "Greyson", "Camden", "Roman", "Elias", "Luca", "Kai", "Kayden", "Bentley", "Vincent", "Robert", "Bryce", "Jude", "Brandon", "Emmett", "Everett", "Jake", "Jonah", "Wesley", "Finn", "Weston", "Silas", "Ben", "Jameson", "Santiago", "Leonardo", "Bennett", "George", "Damian", "Theodore", "Charles", "Kaiden", "Maddox", "Sam", "Theo", "Xander", "Brantley", "Hayden", "Jax", "Rileyå", "Aidan", "Maxwell", "Jayce", "Marcus", "Graham", "Abel", "Colin", "Kingston", "Ashton", "Braxton", "Caden", "Calvin", "Ryker", "Bryson", "Kyle", "Kaleb", "King", "Kaden", "Malachi", "Patrick"}; 

string girlFirstNames[FNAME_NUM] = {"Emma", "Olivia", "Sophia", "Ava", "Mia", "Isabella", "Charlotte", "Amelia", "Harper", "Emily", "Madison", "Abigail", "Avery", "Lily", "Ella", "Sofia", "Chloe", "Evelyn", "Aria", "Scarlett", "Aubrey", "Ellie", "Zoey", "Zoe", "Elizabeth", "Hannah", "Grace", "Addison", "Audrey", "Riley", "Mila", "Layla", "Nora", "Victoria", "Natalie", "Lucy", "Penelope", "Lillian", "Brooklyn", "Savannah", "Claire", "Anna", "Violet", "Leah", "Stella", "Maya", "Skylar", "Alice", "Maria", "Samantha", "Sarah", "Eva", "Sadie", "Sophie", "Madelyn", "Kennedy", "Hazel", "Hailey", "Julia", "Gabriella", "Aaliyah", "Mackenzie", "Paisley", "Bella", "Caroline", "Eleanor", "Peyton", "Kylie", "Ariana", "Clara", "Piper", "Arianna", "Cora", "Kaylee", "Taylor", "Autumn", "Isabelle", "Camila", "Quinn", "Annabelle", "Alyssa", "Aurora", "Emilia", "Alexa", "Lydia", "Isla", "Naomi", "Ruby", "Valentina", "Allison", "Elena", "Alexis", "Gianna", "Luna", "Madeline", "Eliana", "Aubree", "Hadley", "Lilly", "Sydney", "Reagan", "Bailey", "Vivian", "Serenity", "Faith", "Rylee", "Nevaeh", "Kayla", "Willow", "Ivy", "Brielle", "Isabel", "Kinsley", "Sara", "Molly", "Alexandra", "Morgan", "London", "Liliana", "Lyla", "Jade", "Everly", "Adalyn", "Delilah", "Paige", "Lauren", "Brooke", "Natalia", "Emery", "Jasmine", "Ana", "Khloe", "Gracie", "Kate", "Melody", "Adeline", "Arya", "Jordyn", "Norah", "Melanie", "Eden", "Charlie", "Adalynn", "Athena", "Abby", "Maggie", "Laila", "Mya", "Elise", "Reese", "Jocelyn", "Sienna", "Eliza", "Rose", "Katherine", "Josephine", "Brianna", "Makayla", "Lola", "Mary", "Kendall", "Nur", "Andrea", "Payton", "Ariel", "Mckenzie", "Alaina", "Callie", "Gabrielle", "Juliana", "Emerson", "Lila", "Hayden", "Nicole", "Adelyn", "Trinity", "Cecilia", "Genesis", "Alana", "Evie", "Alina", "Arabella", "Leilani", "Genevieve", "Tessa", "Laura", "Lucia", "Nina", "Presley", "Keira", "Alexandria", "Summer", "Fiona", "Teagan", "Iris", "Parker", "Leila", "Juliette", "Kaitlyn", "Marley"}
