/*
    Programmer: Raymond Muller
    Part of the Profiler project.
    This is the main program, where the shell is run.
*/

#include <iostream>
#include <string>

#include "art.h"
#include "database.h"


using namespace std;

void viewHelp(){
    cout << "COMMANDS are CASE SENSITIVE.  Lowercase only!\n";
    cout << "COMMAND KEY:\n";
    cout << "\"q\" or \"quit\": Quits the shell and the program.\n";
    cout << "\"s\" or \"search\": Search by appearance.\n";
    cout << "\"i\" or \"id\": Search by ID.\n";
    cout << "\"h\" or \"help\": Brings up the command key.\n";
    cout << "\"g\" or \"generate\": Generates a new database.\n";
    cout << "\"c\" or \"credits\": Displays credits.\n"; 
    cout << "\"about\": Brings up information about the profiler.\n";
}

//Ask for appearance and search.
void searchMain(){
    int searchID = returnIDFromAppearance();
    tPerson searchedPerson = readDatabase(searchID);
    //Display the Person
    cout << searchedPerson.name << endl;
    cout << searchedPerson.fact << endl;
    cout << "Age: " << searchedPerson.age << endl;
    cout << "Occupation: " << searchedPerson.occupation << endl;
    cout << "Income: $" << searchedPerson.income << endl;
}

void searchByID(){
    int ID;
    cout << "ID?\n";
    cin >> ID;
    tPerson searchedPerson = readDatabase(ID);
    //Display the Person
    cout << searchedPerson.name << endl;
    cout << searchedPerson.fact << endl;
    cout << "Age: " << searchedPerson.age << endl;
    cout << "Occupation: " << searchedPerson.occupation << endl;
    cout << "Income: $" << searchedPerson.income << endl;
}
void viewAbout(){
    aboutSplash();
    cout << "This program simulates a facial recognition system that takes a user's face than compares it to a database to get the user's identity.\n";
    cout << "This database could be stored on the web (using existing services like Facebook or IMDb), or on a separate server.\n";
    cout << "The program was inspired by the video game Watch_Dogs.\n";
}

void viewCredits(){
    cout << "PROGRAM CREDITS:\n";
    cout << "Programmer: Raymond Muller (webcrawlr)\n";
    cout << "Naming Information: US Census\n";
    cout << "Last Names: Mongobay\n";
    cout << "First Names: Baby Center\n";
    cout << "All profiles are fictional and randomly generated.  Any resemblance to real-life people is unintentional.\n";
    cout << "Any racism, sexism, or other prejudice is generated by the computer, not the developer.  Please don't sue him.";
    cout << "No Shiba Inus were harmed in the making of this program.\n";
    cout << endl;
    cout << "Source code and future updates are available on GitHub: https://github.com/webcrawlr/Profilr\n";
}
//The shell that runs all other commands
void mainShell(){
    bool exit = false;
    while(!exit){
        string cmd; //The command that the 
        cout << ">";
        getline(cin, cmd);
        if(cmd == "q" || cmd == "quit"){
            exit = true;
        }
        else if(cmd == "s" || cmd == "search"){
            searchMain();
        }
        else if(cmd == "i" || cmd == "id"){
            searchByID();
        }
        else if(cmd == "h" || cmd == "help"){
            viewHelp();
        }
        else if(cmd == "g" || cmd == "generate"){
            bool clear = false;
            char answer = 'T';
            int sentinel = -1;
            while(toupper(answer) != 'Y' && toupper(answer) != 'N'){
                cout << "Are you sure you want to generate a new database? (Y/N):\n";
                cin >> answer;
			
                if(toupper(answer) == 'Y'){
				    clear = true; //Proceed to generate new database.
                }
                else if(toupper(answer) == 'N'){
                    cout << "Cancelling command...\n";
                }
                else{
                    cout << "Invalid input.\nPlease type only \"Y\" or \"N\"." << endl;
                }
            }
            if(clear){
                int size;
                cout << "Enter the size of the database (NOTE: Larger databases may take time to generate):\n";
                cin >> size;
                if(size == sentinel){
                    break;
                }
                else{
                    generateNewDatabase(size);
                }
            }
        }
        else if(cmd == "about"){
            viewAbout();
        }
        else if (cmd == "c" || cmd == "credits"){
            viewCredits();
        }
        else if(cmd == "doge" || cmd == "shibe"){
        	cout << "─────────▄──────────────▄" << endl;
            cout << "────────▌▒█───────────▄▀▒▌" << endl;
            cout << "────────▌▒▒▀▄───────▄▀▒▒▒▐" << endl;
            cout << "───────▐▄▀▒▒▀▀▀▀▄▄▄▀▒▒▒▒▒▐" << endl;
            cout << "─────▄▄▀▒▒▒▒▒▒▒▒▒▒▒█▒▒▄█▒▐" << endl;
            cout << "───▄▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀██▀▒▌" << endl;
            cout << "──▐▒▒▒▄▄▄▒▒▒▒▒▒▒▒▒▒▒▒▒▀▄▒▒▌" << endl;
            cout << "──▌▒▒▐▄█▀▒▒▒▒▄▀█▄▒▒▒▒▒▒▒█▒▐" << endl;
            cout << "─▐▒▒▒▒▒▒▒▒▒▒▒▌██▀▒▒▒▒▒▒▒▒▀▄▌" << endl;
            cout << "─▌▒▀▄██▄▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒▌" << endl;
            cout << "─▌▀▐▄█▄█▌▄▒▀▒▒▒▒▒▒░░░░░░▒▒▒▐" << endl;
            cout << "▐▒▀▐▀▐▀▒▒▄▄▒▄▒▒▒▒▒░░░░░░▒▒▒▒▌" << endl;
            cout << "▐▒▒▒▀▀▄▄▒▒▒▄▒▒▒▒▒▒░░░░░░▒▒▒▐" << endl;
            cout << "─▌▒▒▒▒▒▒▀▀▀▒▒▒▒▒▒▒▒░░░░▒▒▒▒▌" << endl;
            cout << "─▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐" << endl;
            cout << "──▀▄▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▄▒▒▒▒▌" << endl;
            cout << "────▀▄▒▒▒▒▒▒▒▒▒▒▄▄▄▀▒▒▒▒▄▀" << endl;
            cout << "───▐▀▒▀▄▄▄▄▄▄▀▀▀▒▒▒▒▒▄▄▀" << endl;
            cout << "──▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀▀" << endl;
        }
        else{
            cout << endl;
        }
    }
}
int main(){
    //Startup sequence
    startSplash();
    cout << "> New to using the Profiler?  Type \"h\" for help.\n";
    mainShell();
}

